# Specify the main script used to create a new PDF.JS web worker.
# In production, leave this undefined or change it to point to the
# combined `pdf.worker.js` file.
PDFJS.workerSrc = '/npb-pdfjs-example/scripts/pdf.worker.js'
#
# See README for overview
#
#
# Fetch the PDF document from the URL using promises
#
PDFJS.getDocument '/npb-pdfjs-example/PDF/test.pdf'
.then (pdf) ->
  # Using promise to fetch the page
  pdf.getPage 1
  .then (page) ->
    scale = 1.5
    viewport = page.getViewport scale
    #
    # Prepare canvas using PDF page dimensions
    #
    canvas = document.getElementById 'the-canvas'
    context = canvas.getContext '2d'
    canvas.height = viewport.height
    canvas.width = viewport.width
    #
    # Render PDF page into canvas context
    #
    renderContext =
      canvasContext: context
      viewport: viewport
    page.render renderContext
    return
  return

# ---
# generated by js2coffee 2.0.0