# Specify the main script used to create a new PDF.JS web worker.
# In production, change this to point to the combined `pdf.js` file.
PDFJS.workerSrc = '../../scripts/pdf.worker.js'
# Specify the PDF with AcroForm here
pdfWithFormsPath = '../../PDF/test.pdf'

# ---
# generated by js2coffee 2.0.0