CSS_UNITS = 96.0 / 72.0
DEFAULT_SCALE = 'auto'
UNKNOWN_SCALE = 0
MAX_AUTO_SCALE = 1.25
SCROLLBAR_PADDING = 40
VERTICAL_PADDING = 5

PresentationModeState =
  UNKNOWN: 0
  NORMAL: 1
  CHANGING: 2
  FULLSCREEN: 3
IGNORE_CURRENT_POSITION_ON_ZOOM = false
DEFAULT_CACHE_SIZE = 10
CLEANUP_TIMEOUT = 30000
RenderingStates =
  INITIAL: 0
  RUNNING: 1
  PAUSED: 2
  FINISHED: 3

TEXT_LAYER_RENDER_DELAY = 200 # ms

MAX_TEXT_DIVS_TO_RENDER = 100000

NonWhitespaceRegexp = /\S/